package rules;
import com.currentbp.entry.Student;

rule "aaa1"
    when
        student: Student( score >= 60)
    then
        student.setDescription("好学生");
end

rule "ccc1"
    when
        student: Student( score < 60)
    then
        System.out.println("++1");
       student.setDescription("差学生");
end

rule "ccc2"
    when
        student: Student( score < 60 && sex == 2)
    then
    System.out.println("++2");
       student.setDescription("男差学生");
end
